### ISSUE TITLE
[Suggestion] A few ideas I think you might like

### ISSUE THREAD

**Issue by SylisMC** [Hephaestus-Dev/TinyTweaks#45]
I got so excited when I found this mod! you did a really good job! and you condensed my mod folder by a lot! really looking forward to the development of this mod!

I had a few ideas that you might be interested in! 
- Livestock Grazing | Livestalk will eat crops off of farmed land
- Torch key | Keybind to place a torch from your inventory
- Breeding toggle | Livestalk will breed from eating crops
- Villager auto butcher | butchers would breed and harvest meat storing in chests around the village
- True Tree climbing | exclusive to logs with leaves on them
- Automatic doors | Doors automatically open when players walk through them (would pair nicely with double doors)
- Useful cauldrons | Disable filling water bottles from non-cauldrons
- Cactus farming | (same as sugarcane)
- Snowy trees | Generate snow under trees in snowy biomes (vanilla only spawns snow on top of trees and it looks ridiculous)
- Snow piles | (when snowing, snow could have a chance to build up a few layers)
- Falling leaves | When mining a tree, leaves will fall to the ground (like sand) before degenerating
- instant grass | Right-click dirt with seeds to make grass
- Dirt paths | Right-click dirt with a shovel to make it a path
- Silk spawners | Age-old mining of spawners with silk touch
- Suit up | Shift-clicking armor stands will quick swap gear
- Clean waterlog | waterlogged blocks won't leave a water source block when broken
- Imperishable | Enchantment preventing you from using a tool that is at 1 durability Credit: V-Tweaks
- Realistic predators | when wolves/ocelots kill mobs for food, they will actually eat the food instead of leaving it on the ground  Credit: VanillaTweaks
- Hot pockets | Customizable nether lava pockets, bigger pockets, or turn them off altogether (one block of lava when mining) Credit: VanillaTweaks

Thanks for doing such a wonderful job so far!

**Comment by K0-RR** [comment]
Snowy trees
Snow piles
Falling leaves
Realistic predators

I would love to see these.

**Comment by Haven-King** [comment]
Here are my thoughts on these:
✔️ Livestock Grazing: Seems like a decent feature, I'll add it to the list
❌ Torch key: Not really in-scope for TinyTweaks, I don't think
✔️ Breeding Toggle: Seems like this goes hand in hand with livestock grazing
❌ Villager auto butcher: Neat idea, though adding the farmer villagers was a bit of a pain. If I did this, I might just separate all the villagers who have jobs out into a separate mod
✔️ True Tree Climbing: It actually used to work like this, I just changed it to make it easier for myself, but I'll go ahead and change it back
✔️ Automatic doors: I'll add this to the list
❌ Useful Cauldrons: Doesn't seem great to me
✔️ Cactus Farming: Sure
✔️ Snowy Trees: I'll look into it
❌ Snow Piles: People seem to like this mod working *mostly* serverside, and this would screw that up, so I'll have to skip this one.
✔️ Falling Leaves: Neat idea, I'll look into it
❌ Instant Grass: Seems OP to me 😛 
✔️ Dirt Paths: Sure, why not
❌ Silk Spawners: This doesn't seem to be in scope for Tiny Tweaks
✔️ Suit Up: Sure, why not.
❌ Clean Waterlog: Nah, this is intentional IMO
❌ Imperishable: I don't want to "add" content like this, mostly for the serversided aspect
✔️ Realistic Predators: Wolves actually already do this! I can go ahead and add the behavior to ocelots as well.
❌ Hot Pockets: Worldgen stuff doesn't seem like it goes here really.

**Comment by SylisMC** [comment]
Thanks for taking the time to review! this is honestly one of my favorite mods and I can tell you put time and care into your work, thanks for the awesome mod!

**Comment by Haven-King** [comment]
I've added most of the ones I approved before in [1.2.0](https://www.curseforge.com/minecraft/mc-mods/tinytweaks/files/3198708). I chose not to add the following:
- Cactus Farming - Most of the other blocks are instabreak (cocoabeans excepted) so I decided cactus wasn't the best fit
- Dirt Paths - The paths are grass, so I decided I'd rather keep that vanilla consistency

Thanks for the ideas!
