### ISSUE TITLE
[Compatibility][Crash] with carpet-addons

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Hephaestus-Dev/TinyTweaks#49]
Crashes on startup when using [carpet-addons](https://github.com/whoImT/carpet-addons)
[latest.log](https://pastebin.com/sNBhuMU3)
Mod list for testing
```
fabric-api-0.29.1+1.16.jar
tinytweaks-1.1.2.jar
carpet-addons-1.16.3-1.0.4+v201021.jar
fabric-carpet-1.16.4-1.4.17+v201111.jar
```

**Comment by Haven-King** [comment]
This is due to Carpet Addons [overwriting the method I'm injecting into](https://github.com/whoImT/carpet-addons/blob/3e973f9bbc69e10a6daf2b72a1a325a580ebbebe/src/main/java/carpetaddons/mixins/BlockMixin.java#L43). I could just not load that mixin if Carpet Addons is present, but it would be better for them to fix it on their end.

**Comment by supersaiyansubtlety** [comment]
I'll open an issue on their repo. 
The only reason I didn't in the first place is that carpet and its addons all use a command-based config system and I don't know that's checked early enough to disable mixins.

**Comment by Haven-King** [comment]
It would be better if they just didn't use an overwrite at all, disabled or not.

**Comment by supersaiyansubtlety** [comment]
Just noticed this is still open... no more.
